# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('weekday', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set([('restaurant', 'weekday', 'from_hour', 'to_hour')]),
        ),
    ]
