# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171125_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together=set([('restaurant', 'weekday')]),
        ),
    ]
