# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0003_auto_20171119_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_of_dish', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('main_ingredient', models.CharField(blank=True, max_length=200, null=True)),
                ('region_or_state', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], default=0, max_length=1)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Item'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Category'),
        ),
    ]
